<a href="https://colab.research.google.com/github/KonradSzkliniarz/Bootcamp/blob/master/2_Algebra_liniowa.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Norma wektora, długość wektora w przestrzeni R^2

In [0]:
import numpy as np


In [0]:
v1= np.array([0,4])
# 0 i 4 to współrzędne wektora

In [3]:
v1

array([0, 4])

In [4]:
np.linalg.norm(v1)
#norma wektora = 4

4.0

In [0]:
#norma w przestrzeni R^N. Przestrzeń 3 wymiarowa
v2= np.array([-10,10,13])

In [6]:
np.linalg.norm(v2)

19.209372712298546

## Odległość dwóch punktów na płaszczyźnie

In [0]:
p = np.array([3,0])
q= np.array([0,4])

In [8]:
np.linalg.norm(p-q)

5.0

In [9]:
p = np.array([3,0,1])
q= np.array([0,4,2])
np.linalg.norm(p-q)

5.0990195135927845

## Mnożenie macierzy

In [0]:
X = np.array([[5,3],[3,9]])

In [11]:
X

array([[5, 3],
       [3, 9]])

In [0]:
Y = np.array([[1],[-1]])

In [13]:
Y

array([[ 1],
       [-1]])

In [0]:
Z =np.dot(X,Y)

In [15]:
Z

array([[ 2],
       [-6]])

In [16]:
Z.shape

(2, 1)

In [0]:
# więcej wymiarów
X = np.array([[2,-1,3],[3,1,0]])

In [18]:
X

array([[ 2, -1,  3],
       [ 3,  1,  0]])

In [0]:
Y = np.array([[2,1,-1],[0,-1,2],[3,2,0]])

In [20]:
Y

array([[ 2,  1, -1],
       [ 0, -1,  2],
       [ 3,  2,  0]])

In [21]:
np.dot(X,Y)

array([[13,  9, -4],
       [ 6,  2, -1]])

## Wyznancznik macierzy
|A| <- oznaczenie wyznacznika
wyznacznik oblicza się po skosie (czyli działa tylko w kwadratowych macierzach) przemnażając od lewej górnej krawędzi po skosie a później do tego dodajemy ponowanie po skosie ale piętro niżej itd, a potem takie same składniki po skosie odejmujemy :D

In [0]:
A= np.array([[2,4],[-1,3]])

In [25]:
A

array([[ 2,  4],
       [-1,  3]])

In [26]:
np.linalg.det(A)

9.999999999999998

## Ślad macierzy
Suma elementów na przekątnej

In [27]:
np.trace(A)

5

## Macierz jednostkowa
### Macierz kwadratowa, która składa się z jedynek i zer po przekątnej

In [28]:
np.eye(5,dtype='int')

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

## Macierz odwrotna
pomnożenie macierzy razy macierz odwrotną daje macierz jednostkową. AB = BA

In [29]:
A

array([[ 2,  4],
       [-1,  3]])

In [0]:
B = np.linalg.inv(A)

In [31]:
B

array([[ 0.3, -0.4],
       [ 0.1,  0.2]])

In [34]:
np.set_printoptions(precision=4, suppress=True)
np.dot(A,B)

array([[1., 0.],
       [0., 1.]])

In [35]:
np.dot(B,A)

array([[ 1., -0.],
       [ 0.,  1.]])

## Macierz transponowana
Zamiana wierszy na kolumny i kolumn na wiersze

In [36]:
A

array([[ 2,  4],
       [-1,  3]])

In [37]:
np.transpose(A)

array([[ 2, -1],
       [ 4,  3]])

In [38]:
A.T

array([[ 2, -1],
       [ 4,  3]])

## Rozwiązywanie układów równań

Układ równań:


```
2x + 4y = 10
x - y = -1
```

Możemy przedstawić macierzowo z kwadratową macierzą współczyników
```
2  4
1 -1
```


In [41]:
A = np.array([[2,4],[1,-1]])
print(A,'macierz współczynników')

[[ 2  4]
 [ 1 -1]] macierz współczynników


In [43]:
B = np.array([[10],[-1]])
print(B, 'wektor wyrazów wolnych')

[[10]
 [-1]] wektor wyrazów wolnych


Ogólny wzór <br>

**AX = B <br>** <br>
Obie strony mnożymy razy A^1 - dzięki temu skracamy A po lewej,bo wychodzi macierz jednostkowa <br>

**A^-1 * AX = A^-1 * B <br>**
<br>
i ostateczny wzór na X jest jak poniżej <br>

**X = A^-1 * B**

Teraz szukamy macierzy odwrotnej do macierzy A

In [0]:
A_inv = np.linalg.inv(A)

In [0]:
# poniższe działanie wynika ze wzoru

X = np.dot(A_inv,B)

In [48]:
# a to jest wynik
X

array([[1.],
       [2.]])

In [49]:
X.shape

(2, 1)