<a href="https://colab.research.google.com/github/KonradSzkliniarz/Bootcamp/blob/master/2_Algebra_liniowa.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Norma wektora, długość wektora w przestrzeni R^2

In [ ]:
import numpy as np


In [ ]:
v1= np.array([0,4])
# 0 i 4 to współrzędne wektora

In [ ]:
v1

array([0, 4])

In [ ]:
np.linalg.norm(v1)
#norma wektora = 4

4.0

In [ ]:
#norma w przestrzeni R^N. Przestrzeń 3 wymiarowa
v2= np.array([-10,10,13])

In [ ]:
np.linalg.norm(v2)

19.209372712298546

## Odległość dwóch punktów na płaszczyźnie

In [ ]:
p = np.array([3,0])
q= np.array([0,4])

In [ ]:
np.linalg.norm(p-q)

5.0

In [ ]:
p = np.array([3,0,1])
q= np.array([0,4,2])
np.linalg.norm(p-q)

5.0990195135927845

## Mnożenie macierzy

In [ ]:
X = np.array([[5,3],[3,9]])

In [ ]:
X

array([[5, 2],
       [3, 9]])

In [ ]:
Y = np.array([[1],[-1]])

In [ ]:
Y

array([[ 1],
       [-1]])

In [ ]:
Z =np.dot(X,Y)

In [ ]:
Z

array([[ 2],
       [-6]])

In [ ]:
Z.shape

(2, 1)

In [ ]:
# więcej wymiarów
X = np.array([[2,-1,3],[3,1,0]])

In [ ]:
X

array([[ 2, -1,  3],
       [ 3,  1,  0]])

In [ ]:
Y = np.array([[2,1,-1],[0,-1,2],[3,2,0]])

In [ ]:
Y

array([[ 2,  1, -1],
       [ 0, -1,  2],
       [ 3,  2,  0]])

In [ ]:
np.dot(X,Y)

array([[13,  9, -4],
       [ 6,  2, -1]])