<a href="https://colab.research.google.com/github/KonradSzkliniarz/Bootcamp/blob/master/Tablice_NumPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# NumPy ndarray

## Teoria

In [ ]:
import numpy as np
np.__version__

'1.18.4'

In [ ]:
#sprawdzanie klas, metod, atrybutów w np
print(dir(np))

['ALLOW_THREADS', 'AxisError', 'BUFSIZE', 'CLIP', 'ComplexWarning', 'DataSource', 'ERR_CALL', 'ERR_DEFAULT', 'ERR_IGNORE', 'ERR_LOG', 'ERR_PRINT', 'ERR_RAISE', 'ERR_WARN', 'FLOATING_POINT_SUPPORT', 'FPE_DIVIDEBYZERO', 'FPE_INVALID', 'FPE_OVERFLOW', 'FPE_UNDERFLOW', 'False_', 'Inf', 'Infinity', 'MAXDIMS', 'MAY_SHARE_BOUNDS', 'MAY_SHARE_EXACT', 'MachAr', 'ModuleDeprecationWarning', 'NAN', 'NINF', 'NZERO', 'NaN', 'PINF', 'PZERO', 'RAISE', 'RankWarning', 'SHIFT_DIVIDEBYZERO', 'SHIFT_INVALID', 'SHIFT_OVERFLOW', 'SHIFT_UNDERFLOW', 'ScalarType', 'Tester', 'TooHardError', 'True_', 'UFUNC_BUFSIZE_DEFAULT', 'UFUNC_PYVALS_NAME', 'VisibleDeprecationWarning', 'WRAP', '_NoValue', '_UFUNC_API', '__NUMPY_SETUP__', '__all__', '__builtins__', '__cached__', '__config__', '__doc__', '__file__', '__git_revision__', '__loader__', '__name__', '__package__', '__path__', '__spec__', '__version__', '_add_newdoc_ufunc', '_distributor_init', '_globals', '_mat', '_pytesttester', 'abs', 'absolute', 'absolute_import

In [ ]:
#sprawdzanie definicji funkcji
help(np.array)

Help on built-in function array in module numpy:

array(...)
    array(object, dtype=None, copy=True, order='K', subok=False, ndmin=0)
    
    Create an array.
    
    Parameters
    ----------
    object : array_like
        An array, any object exposing the array interface, an object whose
        __array__ method returns an array, or any (nested) sequence.
    dtype : data-type, optional
        The desired data-type for the array.  If not given, then the type will
        be determined as the minimum type required to hold the objects in the
        sequence.
    copy : bool, optional
        If true (default), then the object is copied.  Otherwise, a copy will
        only be made if __array__ returns a copy, if obj is a nested sequence,
        or if a copy is needed to satisfy any of the other requirements
        (`dtype`, `order`, etc.).
    order : {'K', 'A', 'C', 'F'}, optional
        Specify the memory layout of the array. If object is not an array, the
        newly crea

## 1D Array

In [ ]:
x=np.array([1,3])
x

array([1, 3])

In [ ]:
print(x)

[1 3]


In [ ]:
type(x)

numpy.ndarray

In [ ]:
x.ndim

1

In [ ]:
x.shape

(2,)

In [ ]:
x.size

2

In [ ]:
x.dtype

dtype('int64')

In [ ]:
x= np.array([1.3, 2.3, 1.4])

In [ ]:
print(x)

[1.3 2.3 1.4]


In [ ]:
x.dtype

dtype('float64')

## 2D Array

In [ ]:
x= np.array([[1,2],[-3,1]])

In [ ]:
print(x)

[[ 1  2]
 [-3  1]]


In [ ]:
x.ndim

2

In [ ]:
x.shape

(2, 2)

In [ ]:
x.dtype

dtype('int64')

In [ ]:
x=np.array([[1,2,3],[4,2,1]])

In [ ]:
print(x)

[[1 2 3]
 [4 2 1]]


In [ ]:
x.shape

(2, 3)

## 3D Array

In [ ]:
x=np.array(
    [[[1,2,3],
      [3,1,2]],
     
      [[2,1,3],
       [3,1,2]]])

In [ ]:
x

array([[[1, 2, 3],
        [3, 1, 2]],

       [[2, 1, 3],
        [3, 1, 2]]])

In [ ]:
x.ndim

3

In [ ]:
x.shape
# dwa elementy po dwa wiersze po trzy kolumny

(2, 2, 3)

## Typy danych

In [ ]:
A = np.array([1,2,3])

In [ ]:
A.dtype

dtype('int64')

In [ ]:
A = np.array([1.0,2.1,3.5])

In [ ]:
A.dtype

dtype('float64')

In [ ]:
A = np.array([1,2,3], dtype='float')

In [ ]:
A.dtype

dtype('float64')

In [ ]:
A = np.array([1,2,3], dtype='complex')

In [ ]:
A.dtype

dtype('complex128')

In [ ]:
A = np.array([1.0,2.1,3.7], dtype='int')

In [ ]:
A.dtype

dtype('int64')

In [ ]:
A
# uwaga przy konwersji obcina to co po przecinku

array([1, 2, 3])

In [ ]:
A = np.array([1,0],dtype='bool')

In [ ]:
A

array([ True, False])

In [ ]:
A= np.array([24,120,230], dtype='int8')

In [ ]:
A.dtype

dtype('int8')

In [ ]:
A= np.array([24,120,230], dtype='uint8')

In [ ]:
A.dtype

dtype('uint8')

## Tworzenie tablic

In [ ]:
np.zeros(shape=(4,10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [ ]:
np.zeros(shape=(4,10), dtype='int')

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [ ]:
np.ones(shape=(5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [ ]:
np.full(shape=(3,3),fill_value=4, dtype='int')

array([[4, 4, 4],
       [4, 4, 4],
       [4, 4, 4]])

In [ ]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
range(10)

range(0, 10)

In [ ]:
list(range(10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [ ]:
np.arange(start=5,stop=10)

array([5, 6, 7, 8, 9])

In [ ]:
np.arange(start=2, stop=24, step=2)

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22])

In [ ]:
np.arange(100,20,-5)

array([100,  95,  90,  85,  80,  75,  70,  65,  60,  55,  50,  45,  40,
        35,  30,  25])

In [ ]:
np.arange(0,1,0.05)

array([0.  , 0.05, 0.1 , 0.15, 0.2 , 0.25, 0.3 , 0.35, 0.4 , 0.45, 0.5 ,
       0.55, 0.6 , 0.65, 0.7 , 0.75, 0.8 , 0.85, 0.9 , 0.95])

In [ ]:
np.linspace(start=0, stop=1, num=5)
# nie podajemy kroku a ilość kroków

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [ ]:
A = np.arange(15)

In [ ]:
A

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [ ]:
A.reshape(3,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [ ]:
A.reshape(3,-1)
# -1 oznacza, że Python ma sobie sam dobrać ilość elementów w wierszu wg tej ilości wierszów jaką podaliśmy

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [ ]:
A.reshape(-1,3)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

## Operacje na tablicach

In [ ]:
A= np.array([3,1,4,2])

In [ ]:
B=np.array([3,-1,3,2])

In [ ]:
print(A,B)

[3 1 4 2] [ 3 -1  3  2]


In [ ]:
A+B

array([6, 0, 7, 4])

In [ ]:
A-B

array([0, 2, 1, 0])

In [ ]:
A*B

array([ 9, -1, 12,  4])

In [ ]:
A/B

array([ 1.        , -1.        ,  1.33333333,  1.        ])

In [ ]:
np.add(A,B)

array([6, 0, 7, 4])

In [ ]:
np.subtract(A,B)

array([0, 2, 1, 0])

In [ ]:
np.multiply(A,B)

array([ 9, -1, 12,  4])

In [ ]:
np.divide(A,B)

array([ 1.        , -1.        ,  1.33333333,  1.        ])

In [ ]:
A + 3

array([6, 4, 7, 5])

In [ ]:
A-2

array([ 1, -1,  2,  0])

In [ ]:
A*2

array([6, 2, 8, 4])

In [ ]:
A+3*B

array([12, -2, 13,  8])

#### Mnożenie macierzowe

In [ ]:
X = np.array([[1,3],[-2,0]])

In [ ]:
Y = np.array([[6,0],[-1,2]])

In [ ]:
print(X,'\n'*2,Y)

[[ 1  3]
 [-2  0]] 

 [[ 6  0]
 [-1  2]]


In [ ]:
# mnożenie standardowe
X * Y

array([[6, 0],
       [2, 0]])

In [ ]:
#mnożenie macierzowe
np.dot(X,Y)

array([[  3,   6],
       [-12,   0]])

In [ ]:
X.dot(Y)

array([[  3,   6],
       [-12,   0]])

In [ ]:
Y.dot(X)

array([[ 6, 18],
       [-5, -3]])

In [ ]:
# inny sposób polecenia za pomocą małpy
X @ Y

array([[  3,   6],
       [-12,   0]])

## Generowanie list pseudolosowych

Ziarno losowania to parametr pozwalający otrzymać przy każdym losowaniu tę samą wartość

In [ ]:
np.random.seed(0)

In [ ]:
np.random.randn(10)
# zwraca n wartości z rozkładu losowego

array([ 1.76405235,  0.40015721,  0.97873798,  2.2408932 ,  1.86755799,
       -0.97727788,  0.95008842, -0.15135721, -0.10321885,  0.4105985 ])

In [ ]:
np.random.randn(10,4)
#parametrami określamy liczbę kolumn i wierszy

array([[ 0.14404357,  1.45427351,  0.76103773,  0.12167502],
       [ 0.44386323,  0.33367433,  1.49407907, -0.20515826],
       [ 0.3130677 , -0.85409574, -2.55298982,  0.6536186 ],
       [ 0.8644362 , -0.74216502,  2.26975462, -1.45436567],
       [ 0.04575852, -0.18718385,  1.53277921,  1.46935877],
       [ 0.15494743,  0.37816252, -0.88778575, -1.98079647],
       [-0.34791215,  0.15634897,  1.23029068,  1.20237985],
       [-0.38732682, -0.30230275, -1.04855297, -1.42001794],
       [-1.70627019,  1.9507754 , -0.50965218, -0.4380743 ],
       [-1.25279536,  0.77749036, -1.61389785, -0.21274028]])

In [ ]:
np.random.rand()
#zwraca z przedziału 0/1

0.15896958364551972

In [ ]:
np.random.rand(10)

array([0.11037514, 0.65632959, 0.13818295, 0.19658236, 0.36872517,
       0.82099323, 0.09710128, 0.83794491, 0.09609841, 0.97645947])

In [ ]:
np.random.rand(10,2)

array([[0.4686512 , 0.97676109],
       [0.60484552, 0.73926358],
       [0.03918779, 0.28280696],
       [0.12019656, 0.2961402 ],
       [0.11872772, 0.31798318],
       [0.41426299, 0.0641475 ],
       [0.69247212, 0.56660145],
       [0.26538949, 0.52324805],
       [0.09394051, 0.5759465 ],
       [0.9292962 , 0.31856895]])

In [ ]:
np.random.randint(10)
# zwraca liczbę całkowitą do wartości podanej w parametrze (od 0 do 10 w tym przypadku)

2

In [ ]:
np.random.randint(low=10, high=101)

61

In [ ]:
np.random.randint(low=10, high=101, size=(3,5))

array([[90, 42, 64, 10, 48],
       [29, 56, 52, 66, 70],
       [87, 40, 34, 12, 13]])

In [ ]:
np.random.choice([4,2,1,2])
#zwraca losowy element z listy

1

In [ ]:
np.random.choice(['python','java','sql'])

'sql'

In [ ]:
data=np.arange(10)

In [ ]:
data

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.random.shuffle(data)

In [ ]:
data

array([1, 6, 5, 4, 2, 7, 3, 9, 8, 0])

## Podstawowe funkcje w numpy

In [ ]:
# exponent
np.exp(1)

2.718281828459045

In [ ]:
# pierwiastek
np.sqrt(9)

3.0

In [ ]:
# operator logiczny
np.all([2,3,0])

False

In [ ]:
np.all([2,3,1])

True

In [ ]:
np.any([2,3,0])

True

In [ ]:
bool(0)

False

In [ ]:
A = np.random.rand(5)

In [ ]:
A

array([0.89155444, 0.68005557, 0.44919774, 0.97857093, 0.11620191])

In [ ]:
np.argmax(A)
# zwraca numer indeksu o największej wartości

3

In [ ]:
A[np.argmax(A)]

0.978570928420717

In [ ]:
A.max()

0.978570928420717

In [ ]:
np.argmin(A)

4

In [ ]:
A

array([0.89155444, 0.68005557, 0.44919774, 0.97857093, 0.11620191])

In [ ]:
np.argsort(A)
# informuje na temat rosnącej kolejności, tj na pierwszym miejscu element, drugi, na drugim czwarty, na trzecim zerowy itd

array([4, 2, 1, 0, 3])

In [ ]:
np.mean(A)

0.6231161165881146

In [ ]:
np.median(A)

0.6800555694634123

In [ ]:
np.std(A)

0.3126848164219005

## Indeksowanie i wycinanie tablic

In [ ]:
A = np.arange(20)

In [ ]:
A

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [ ]:
A[4]

4

In [ ]:
A[:3]

array([0, 1, 2])

In [ ]:
A[1:4]

array([1, 2, 3])

In [ ]:
A[[0,2]]

array([0, 2])

In [ ]:
A=A.reshape(4,5)

In [ ]:
A

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [ ]:
A[0]

array([0, 1, 2, 3, 4])

In [ ]:
A[1]

array([5, 6, 7, 8, 9])

In [ ]:
#zwracanie danych z kolumny
A[:,0]

array([ 0,  5, 10, 15])

In [ ]:
#ostatnia kolumna
A[:,-1]

array([ 4,  9, 14, 19])

In [ ]:
# ostatni wiersz, ostatnia kolumna
A[-1,-1]

19

In [ ]:
A[1][1]

6

In [ ]:
# Przedział - uwaga na górną granicę
A[1:3,1:4]

array([[ 6,  7,  8],
       [11, 12, 13]])

In [ ]:
A[1,2]=14

In [ ]:
A

array([[ 0,  1,  2,  3,  4],
       [ 5,  6, 14,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

## Iteracja po tablicach

In [ ]:
for row in A:
  print(row)

[0 1 2 3 4]
[ 5  6 14  8  9]
[10 11 12 13 14]
[15 16 17 18 19]


In [ ]:
for row in A:
  print(row[0])

0
5
10
15


In [ ]:
for row in A:
  print(row[0:3])

[0 1 2]
[ 5  6 14]
[10 11 12]
[15 16 17]


In [ ]:
for element in A.flat:
  print(element)

0
1
2
3
4
5
6
14
8
9
10
11
12
13
14
15
16
17
18
19


## Zmiana rozmiaru tablic

In [ ]:
A

array([[ 0,  1,  2,  3,  4],
       [ 5,  6, 14,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [ ]:
A.shape

(4, 5)

In [ ]:
A.reshape(5,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6, 14],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [ ]:
# wypłaszczanie danych
A.ravel()

array([ 0,  1,  2,  3,  4,  5,  6, 14,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [ ]:
# transponowanie 

In [ ]:
A.transpose()

array([[ 0,  5, 10, 15],
       [ 1,  6, 11, 16],
       [ 2, 14, 12, 17],
       [ 3,  8, 13, 18],
       [ 4,  9, 14, 19]])

## Maski logiczne

In [ ]:
A= np.arange(-10,10,0.5)

In [ ]:
A

array([-10. ,  -9.5,  -9. ,  -8.5,  -8. ,  -7.5,  -7. ,  -6.5,  -6. ,
        -5.5,  -5. ,  -4.5,  -4. ,  -3.5,  -3. ,  -2.5,  -2. ,  -1.5,
        -1. ,  -0.5,   0. ,   0.5,   1. ,   1.5,   2. ,   2.5,   3. ,
         3.5,   4. ,   4.5,   5. ,   5.5,   6. ,   6.5,   7. ,   7.5,
         8. ,   8.5,   9. ,   9.5])

In [ ]:
A=A.reshape(10,-1)
A

array([[-10. ,  -9.5,  -9. ,  -8.5],
       [ -8. ,  -7.5,  -7. ,  -6.5],
       [ -6. ,  -5.5,  -5. ,  -4.5],
       [ -4. ,  -3.5,  -3. ,  -2.5],
       [ -2. ,  -1.5,  -1. ,  -0.5],
       [  0. ,   0.5,   1. ,   1.5],
       [  2. ,   2.5,   3. ,   3.5],
       [  4. ,   4.5,   5. ,   5.5],
       [  6. ,   6.5,   7. ,   7.5],
       [  8. ,   8.5,   9. ,   9.5]])

In [ ]:
A > 0

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [ ]:
A[A>0]

array([0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. , 6.5,
       7. , 7.5, 8. , 8.5, 9. , 9.5])

In [ ]:
filter=A>0

In [ ]:
A[filter]

array([0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. , 6.5,
       7. , 7.5, 8. , 8.5, 9. , 9.5])

In [ ]:
np.bitwise_and(A>-5,A<5)

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True, False, False],
       [False, False, False, False],
       [False, False, False, False]])

In [ ]:
A[np.bitwise_and(A>-5,A<5)]

array([-4.5, -4. , -3.5, -3. , -2.5, -2. , -1.5, -1. , -0.5,  0. ,  0.5,
        1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ,  4.5])

In [ ]:
np.bitwise_or(A<-5, A>5)

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])