<a href="https://colab.research.google.com/github/KonradSzkliniarz/Bootcamp/blob/master/Tablice_NumPy_ndarray.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# NumPy ndarray

In [1]:
import numpy as np
np.__version__

'1.18.4'

In [2]:
#sprawdzanie klas, metod, atrybutów w np
print(dir(np))

['ALLOW_THREADS', 'AxisError', 'BUFSIZE', 'CLIP', 'ComplexWarning', 'DataSource', 'ERR_CALL', 'ERR_DEFAULT', 'ERR_IGNORE', 'ERR_LOG', 'ERR_PRINT', 'ERR_RAISE', 'ERR_WARN', 'FLOATING_POINT_SUPPORT', 'FPE_DIVIDEBYZERO', 'FPE_INVALID', 'FPE_OVERFLOW', 'FPE_UNDERFLOW', 'False_', 'Inf', 'Infinity', 'MAXDIMS', 'MAY_SHARE_BOUNDS', 'MAY_SHARE_EXACT', 'MachAr', 'ModuleDeprecationWarning', 'NAN', 'NINF', 'NZERO', 'NaN', 'PINF', 'PZERO', 'RAISE', 'RankWarning', 'SHIFT_DIVIDEBYZERO', 'SHIFT_INVALID', 'SHIFT_OVERFLOW', 'SHIFT_UNDERFLOW', 'ScalarType', 'Tester', 'TooHardError', 'True_', 'UFUNC_BUFSIZE_DEFAULT', 'UFUNC_PYVALS_NAME', 'VisibleDeprecationWarning', 'WRAP', '_NoValue', '_UFUNC_API', '__NUMPY_SETUP__', '__all__', '__builtins__', '__cached__', '__config__', '__doc__', '__file__', '__git_revision__', '__loader__', '__name__', '__package__', '__path__', '__spec__', '__version__', '_add_newdoc_ufunc', '_distributor_init', '_globals', '_mat', '_pytesttester', 'abs', 'absolute', 'absolute_import

In [0]:
#sprawdzanie definicji funkcji
help(np.array)

## 1D Array

In [5]:
x=np.array([1,3])
x

array([1, 3])

In [6]:
print(x)

[1 3]


In [7]:
type(x)

numpy.ndarray

In [8]:
x.ndim

1

In [9]:
x.shape

(2,)

In [10]:
x.size

2

In [11]:
x.dtype

dtype('int64')

In [0]:
x= np.array([1.3, 2.3, 1.4])

In [16]:
print(x)

[1.3 2.3 1.4]


In [18]:
x.dtype

dtype('float64')

## 2D Array

In [0]:
x= np.array([[1,2],[-3,1]])

In [21]:
print(x)

[[ 1  2]
 [-3  1]]


In [22]:
x.ndim

2

In [23]:
x.shape

(2, 2)

In [24]:
x.dtype

dtype('int64')

In [0]:
x=np.array([[1,2,3],[4,2,1]])

In [26]:
print(x)

[[1 2 3]
 [4 2 1]]


In [27]:
x.shape

(2, 3)

## 3D Array

In [0]:
x=np.array(
    [[[1,2,3],
      [3,1,2]],
     
      [[2,1,3],
       [3,1,2]]])

In [32]:
x

array([[[1, 2, 3],
        [3, 1, 2]],

       [[2, 1, 3],
        [3, 1, 2]]])

In [33]:
x.ndim

3

In [35]:
x.shape
# dwa elementy po dwa wiersze po trzy kolumny

(2, 2, 3)