<a href="https://colab.research.google.com/github/KonradSzkliniarz/Bootcamp/blob/master/Tablice_NumPy_ndarray.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# NumPy ndarray

In [36]:
import numpy as np
np.__version__

'1.18.4'

In [37]:
#sprawdzanie klas, metod, atrybutów w np
print(dir(np))

['ALLOW_THREADS', 'AxisError', 'BUFSIZE', 'CLIP', 'ComplexWarning', 'DataSource', 'ERR_CALL', 'ERR_DEFAULT', 'ERR_IGNORE', 'ERR_LOG', 'ERR_PRINT', 'ERR_RAISE', 'ERR_WARN', 'FLOATING_POINT_SUPPORT', 'FPE_DIVIDEBYZERO', 'FPE_INVALID', 'FPE_OVERFLOW', 'FPE_UNDERFLOW', 'False_', 'Inf', 'Infinity', 'MAXDIMS', 'MAY_SHARE_BOUNDS', 'MAY_SHARE_EXACT', 'MachAr', 'ModuleDeprecationWarning', 'NAN', 'NINF', 'NZERO', 'NaN', 'PINF', 'PZERO', 'RAISE', 'RankWarning', 'SHIFT_DIVIDEBYZERO', 'SHIFT_INVALID', 'SHIFT_OVERFLOW', 'SHIFT_UNDERFLOW', 'ScalarType', 'Tester', 'TooHardError', 'True_', 'UFUNC_BUFSIZE_DEFAULT', 'UFUNC_PYVALS_NAME', 'VisibleDeprecationWarning', 'WRAP', '_NoValue', '_UFUNC_API', '__NUMPY_SETUP__', '__all__', '__builtins__', '__cached__', '__config__', '__doc__', '__file__', '__git_revision__', '__loader__', '__name__', '__package__', '__path__', '__spec__', '__version__', '_add_newdoc_ufunc', '_distributor_init', '_globals', '_mat', '_pytesttester', 'abs', 'absolute', 'absolute_import

In [38]:
#sprawdzanie definicji funkcji
help(np.array)

Help on built-in function array in module numpy:

array(...)
    array(object, dtype=None, copy=True, order='K', subok=False, ndmin=0)
    
    Create an array.
    
    Parameters
    ----------
    object : array_like
        An array, any object exposing the array interface, an object whose
        __array__ method returns an array, or any (nested) sequence.
    dtype : data-type, optional
        The desired data-type for the array.  If not given, then the type will
        be determined as the minimum type required to hold the objects in the
        sequence.
    copy : bool, optional
        If true (default), then the object is copied.  Otherwise, a copy will
        only be made if __array__ returns a copy, if obj is a nested sequence,
        or if a copy is needed to satisfy any of the other requirements
        (`dtype`, `order`, etc.).
    order : {'K', 'A', 'C', 'F'}, optional
        Specify the memory layout of the array. If object is not an array, the
        newly crea

## 1D Array

In [39]:
x=np.array([1,3])
x

array([1, 3])

In [40]:
print(x)

[1 3]


In [41]:
type(x)

numpy.ndarray

In [42]:
x.ndim

1

In [43]:
x.shape

(2,)

In [44]:
x.size

2

In [45]:
x.dtype

dtype('int64')

In [0]:
x= np.array([1.3, 2.3, 1.4])

In [47]:
print(x)

[1.3 2.3 1.4]


In [48]:
x.dtype

dtype('float64')

## 2D Array

In [0]:
x= np.array([[1,2],[-3,1]])

In [50]:
print(x)

[[ 1  2]
 [-3  1]]


In [51]:
x.ndim

2

In [52]:
x.shape

(2, 2)

In [53]:
x.dtype

dtype('int64')

In [0]:
x=np.array([[1,2,3],[4,2,1]])

In [55]:
print(x)

[[1 2 3]
 [4 2 1]]


In [56]:
x.shape

(2, 3)

## 3D Array

In [0]:
x=np.array(
    [[[1,2,3],
      [3,1,2]],
     
      [[2,1,3],
       [3,1,2]]])

In [58]:
x

array([[[1, 2, 3],
        [3, 1, 2]],

       [[2, 1, 3],
        [3, 1, 2]]])

In [59]:
x.ndim

3

In [60]:
x.shape
# dwa elementy po dwa wiersze po trzy kolumny

(2, 2, 3)

## Typy danych

In [0]:
A = np.array([1,2,3])

In [62]:
A.dtype

dtype('int64')

In [0]:
A = np.array([1.0,2.1,3.5])

In [64]:
A.dtype

dtype('float64')

In [0]:
A = np.array([1,2,3], dtype='float')

In [67]:
A.dtype

dtype('float64')

In [0]:
A = np.array([1,2,3], dtype='complex')

In [69]:
A.dtype

dtype('complex128')

In [0]:
A = np.array([1.0,2.1,3.7], dtype='int')

In [74]:
A.dtype

dtype('int64')

In [76]:
A
# uwaga przy konwersji obcina to co po przecinku

array([1, 2, 3])

In [0]:
A = np.array([1,0],dtype='bool')

In [80]:
A

array([ True, False])

In [0]:
A= np.array([24,120,230], dtype='int8')

In [84]:
A.dtype

dtype('int8')

In [0]:
A= np.array([24,120,230], dtype='uint8')

In [86]:
A.dtype

dtype('uint8')

## Tworzenie tablic

In [87]:
np.zeros(shape=(4,10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [89]:
np.zeros(shape=(4,10), dtype='int')

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [90]:
np.ones(shape=(5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [91]:
np.full(shape=(3,3),fill_value=4, dtype='int')

array([[4, 4, 4],
       [4, 4, 4],
       [4, 4, 4]])

In [93]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [94]:
range(10)

range(0, 10)

In [95]:
list(range(10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [96]:
np.arange(start=5,stop=10)

array([5, 6, 7, 8, 9])

In [99]:
np.arange(start=2, stop=24, step=2)

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22])

In [100]:
np.arange(100,20,-5)

array([100,  95,  90,  85,  80,  75,  70,  65,  60,  55,  50,  45,  40,
        35,  30,  25])

In [101]:
np.arange(0,1,0.05)

array([0.  , 0.05, 0.1 , 0.15, 0.2 , 0.25, 0.3 , 0.35, 0.4 , 0.45, 0.5 ,
       0.55, 0.6 , 0.65, 0.7 , 0.75, 0.8 , 0.85, 0.9 , 0.95])

In [103]:
np.linspace(start=0, stop=1, num=5)
# nie podajemy kroku a ilość kroków

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [0]:
A = np.arange(15)

In [105]:
A

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [106]:
A.reshape(3,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [108]:
A.reshape(3,-1)
# -1 oznacza, że Python ma sobie sam dobrać ilość elementów w wierszu wg tej ilości wierszów jaką podaliśmy

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [109]:
A.reshape(-1,3)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])